Repository ALgorithmStudy1217/ALSS_SWEA, pull requests merged in 2024-08, with the labels that each got.

#11 [0731] 고영우
  D3/1493/고영우.java
Labels: D3

#13 [0731] 김영진
  D3/1493_김영진.java
  D4/4613_김영진.java
Labels: D3, D4

#14 [0731] 김유민
  D2/1984/youmin.java
  D3/1493/youmin.java
  D3/21131/youmin.java
  D4/4613/youmin.java
Labels: D3, D2, D4

#20 [8월 1주차] 이현정
  D2/1984/hyunjeong.java
  D3/1493/hyunjeong.java
Labels: D3, D2

#23 [8월 1주차] 김영진
  .github/pull_request_template.md
  D2/1859/seokju.java
  D2/1984/hyunjeong.java
  D2/1984/seokju.java
  D2/1984/taehoon.java
  D2/1984/youmin.java
  D3/10726/gahyeon.java
  D3/10726/seokju.java
  D3/10726/taehoon.java
  D3/1493/changmin.java
  D3/1493/gahyeon.java
  D3/1493/hyunjeong.java
  D3/1493/jongheon.java
  D3/1493/seokju.java
  D3/1493/taehoon.java
  D3/1493/youmin.java
  D3/1493/고영우.java
  D3/21131/changmin.java
  D3/21131/jongheon.java
  D3/21131/seokju.java
  D3/21131/taehoon.java
  D3/21131/youmin.java
  D4/3234/jongheon.java
  D4/3234/seokju.java
  D4/3234/taehoon.java
  D4/4613/jongheon.java
  D4/4613/seokju.java
  D4/4613/taehoon.java
  D4/4613/youmin.java
Labels: D3

#24 [8월1주차] 김영진
  D3/1493/김영진.java
  D3/21131/김영진.java
  D4/4613/김영진.java
Labels: D3

#27 [8월 1주차] 김유민
  D3/10726/youmin.java
Labels: D3
